"""
This file contains a function that returns a dictionary whose keys represent the available courses and the values of the keys are again a dictionary whose keys are (years or semesters) and their values are lists containing the instalments to be paid."""


def instalments_per_course(year):
    # THE COMMON INSTALMENTS NAME FOR SEMESTER WISE COURSES
    SEM_COMMON_INSTALMENTS = {
        "SEM1": [f"SEM1 INST1 {year}", f"SEM1 INST2 {year}", f"SEM1 EXAM FEE {year}"],
        "SEM2": [f"SEM2 INST1 {year}", f"SEM2 INST2 {year}", f"SEM2 EXAM FEE {year+1}"],
        "SEM3": [f"SEM3 INST1 {year}", f"SEM3 INST2 {year}", f"SEM3 EXAM FEES {year}"],
        "SEM4": [f"SEM4 INST1 {year}", f"SEM4 INST2 {year}", f"SEM4 EXAM FEE {year+1}"],
        "SEM5": [f"SEM5 INST1 {year}", f"SEM5 INST2 {year}", f"SEM5 EXAM FEE {year}"],
        "SEM6": [f"SEM6 INST1 {year}", f"SEM6 INST2 {year}", f"SEM6 EXAM FEE {year+1}"],
        "SEM7": [f"SEM7 INST1 {year}", f"SEM7 INST2 {year}", f"SEM7 EXAM FEE {year}"],
        "SEM8": [f"SEM8 INST1 {year}", f"SEM8 INST2 {year}", f"SEM8 EXAM FEE {year+1}"],
    }

    # THE COMMON INSTALMENTS NAME FOR YEAR WISE COURSES
    YEAR_COMMON_INSTALMENTS = {
        "YR1": [
            f"YR1 INST1 {year}",
            f"YR1 INST2 {year}",
            f"YR1 INST3 {year}",
            f"YR1 INST4 {year}",
            f"YR1 EXAM FEE {year+1}",
        ],
        "YR2": [
            f"YR2 INST1 {year}",
            f"YR2 INST2 {year}",
            f"YR2 INST3 {year}",
            f"YR2 INST4 {year}",
            f"YR2 EXAM FEE {year+1}",
        ],
        "YR3": [
            f"YR3 INST1 {year}",
            f"YR3 INST2 {year}",
            f"YR3 INST3 {year}",
            f"YR3 INST4 {year}",
            f"YR3 EXAM FEE {year+1}",
        ],
    }

    # MAIN DICTIONARY
    INSTALMENTS_PER_COURSE = {
        # YEAR BASED COURSES
        "YEARLY BCA 701": YEAR_COMMON_INSTALMENTS,
        "YEARLY BBA 601": YEAR_COMMON_INSTALMENTS,
        # ----------------------------------BCOM--------------------------------------------------
        "YEARLY BCom 301 [Computer App- Accounts-Buss. Org]": {
            "YR1": [
                f"YR1 INST1 CSC {year}",
                f"YR1 INST2 CSC {year}",
                f"YR1 INST3 CSC {year}",
                f"YR1 INST4 CSC {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 CSC {year}",
                f"YR2 INST2 CSC {year}",
                f"YR2 INST3 CSC {year}",
                f"YR2 INST4 CSC {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 CSC {year}",
                f"YR3 INST2 CSC {year}",
                f"YR3 INST3 CSC {year}",
                f"YR3 INST4 CSC {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BCom 302 [Tax Procedure- Accounts-Buss Org]": {
            "YR1": [
                f"YR1 INST1 TAX {year}",
                f"YR1 INST2 TAX {year}",
                f"YR1 INST3 TAX {year}",
                f"YR1 INST4 TAX {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 TAX {year}",
                f"YR2 INST2 TAX {year}",
                f"YR2 INST3 TAX {year}",
                f"YR2 INST4 TAX {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 TAX {year}",
                f"YR3 INST2 TAX {year}",
                f"YR3 INST3 TAX {year}",
                f"YR3 INST4 TAX {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BCom 303 [Applied Eco- Accounts-Buss. Org.]": {
            f"YR1": [
                f"YR1 INST1 GEN {year}",
                f"YR1 INST2 GEN {year}",
                f"YR1 INST3 GEN {year}",
                f"YR1 INST4 GEN {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 GEN {year}",
                f"YR2 INST2 GEN {year}",
                f"YR2 INST3 GEN {year}",
                f"YR2 INST4 GEN {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 GEN {year}",
                f"YR3 INST2 GEN {year}",
                f"YR3 INST3 GEN {year}",
                f"YR3 INST4 GEN {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BCom 304 (Honours) Accounts": {
            "YR1": [
                f"YR1 INST1 HON {year}",
                f"YR1 INST2 HON {year}",
                f"YR1 INST3 HON {year}",
                f"YR1 INST4 HON {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 HON {year}",
                f"YR2 INST2 HON {year}",
                f"YR2 INST3 HON {year}",
                f"YR2 INST4 HON {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 HON {year}",
                f"YR3 INST2 HON {year}",
                f"YR3 INST3 HON {year}",
                f"YR3 INST4 HON {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        # BA
        "YEARLY BA 101 [Eco.-Eng. Lit.-Pol. Sci.]": {
            "YR1": [
                f"YR1 INST1 GEN {year}",
                f"YR1 INST2 GEN {year}",
                f"YR1 INST3 GEN {year}",
                f"YR1 INST4 GEN {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 GEN {year}",
                f"YR2 INST2 GEN {year}",
                f"YR2 INST3 GEN {year}",
                f"YR2 INST4 GEN {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 GEN {year}",
                f"YR3 INST2 GEN {year}",
                f"YR3 INST3 GEN {year}",
                f"YR3 INST4 GEN {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 102 [Eco.-Func. Eng.-History]": {
            "YR1": [
                f"YR1 INST1 FEH {year}",
                f"YR1 INST2 FEH {year}",
                f"YR1 INST3 FEH {year}",
                f"YR1 INST4 FEH {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 FEH {year}",
                f"YR2 INST2 FEH {year}",
                f"YR2 INST3 FEH {year}",
                f"YR2 INST4 FEH {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 FEH {year}",
                f"YR3 INST2 FEH {year}",
                f"YR3 INST3 FEH {year}",
                f"YR3 INST4 FEH {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 103 [Eco.-Func. Hindi-History]": {
            "YR1": [
                f"YR1 INST1 GEN {year}",
                f"YR1 INST2 GEN {year}",
                f"YR1 INST3 GEN {year}",
                f"YR1 INST4 GEN {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 GEN {year}",
                f"YR2 INST2 GEN {year}",
                f"YR2 INST3 GEN {year}",
                f"YR2 INST4 GEN {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 GEN {year}",
                f"YR3 INST2 GEN {year}",
                f"YR3 INST3 GEN {year}",
                f"YR3 INST4 GEN {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 104 [Eco.-Func. Hindi-Pol. Sci.]": {
            "YR1": [
                f"YR1 INST1 FEH {year}",
                f"YR1 INST2 FEH {year}",
                f"YR1 INST3 FEH {year}",
                f"YR1 INST4 FEH {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 FEH {year}",
                f"YR2 INST2 FEH {year}",
                f"YR2 INST3 FEH {year}",
                f"YR2 INST4 FEH {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 FEH {year}",
                f"YR3 INST2 FEH {year}",
                f"YR3 INST3 FEH {year}",
                f"YR3 INST4 FEH {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 105 [Eco.-Hindi Lit.-History]": {
            "YR1": [
                f"YR1 INST1 GEN {year}",
                f"YR1 INST2 GEN {year}",
                f"YR1 INST3 GEN {year}",
                f"YR1 INST4 GEN {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 GEN {year}",
                f"YR2 INST2 GEN {year}",
                f"YR2 INST3 GEN {year}",
                f"YR2 INST4 GEN {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 GEN {year}",
                f"YR3 INST2 GEN {year}",
                f"YR3 INST3 GEN {year}",
                f"YR3 INST4 GEN {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 106 [Eco.-Hindi Lit-Pol. Sci.]": {
            "YR1": [
                f"YR1 INST1 GEN {year}",
                f"YR1 INST2 GEN {year}",
                f"YR1 INST3 GEN {year}",
                f"YR1 INST4 GEN {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 GEN {year}",
                f"YR2 INST2 GEN {year}",
                f"YR2 INST3 GEN {year}",
                f"YR2 INST4 GEN {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 GEN {year}",
                f"YR3 INST2 GEN {year}",
                f"YR3 INST3 GEN {year}",
                f"YR3 INST4 GEN {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 107 [Eco.-History-Pol Sci.]": {
            "YR1": [
                f"YR1 INST1 GEN {year}",
                f"YR1 INST2 GEN {year}",
                f"YR1 INST3 GEN {year}",
                f"YR1 INST4 GEN {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 GEN {year}",
                f"YR2 INST2 GEN {year}",
                f"YR2 INST3 GEN {year}",
                f"YR2 INST4 GEN {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 GEN {year}",
                f"YR3 INST2 GEN {year}",
                f"YR3 INST3 GEN {year}",
                f"YR3 INST4 GEN {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 108 [Eng. Lit.-Eco.-History]": {
            "YR1": [
                f"YR1 INST1 GEN {year}",
                f"YR1 INST2 GEN {year}",
                f"YR1 INST3 GEN {year}",
                f"YR1 INST4 GEN {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 GEN {year}",
                f"YR2 INST2 GEN {year}",
                f"YR2 INST3 GEN {year}",
                f"YR2 INST4 GEN {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 GEN {year}",
                f"YR3 INST2 GEN {year}",
                f"YR3 INST3 GEN {year}",
                f"YR3 INST4 GEN {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 109 [Eng. Lit.-History-Pol. Sci.]": {
            "YR1": [
                f"YR1 INST1 GEN {year}",
                f"YR1 INST2 GEN {year}",
                f"YR1 INST3 GEN {year}",
                f"YR1 INST4 GEN {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 GEN {year}",
                f"YR2 INST2 GEN {year}",
                f"YR2 INST3 GEN {year}",
                f"YR2 INST4 GEN {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 GEN {year}",
                f"YR3 INST2 GEN {year}",
                f"YR3 INST3 GEN {year}",
                f"YR3 INST4 GEN {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 112 [C.A.-Eng. Lit.-Eco.]": {
            "YR1": [
                f"YR1 INST1 COA {year}",
                f"YR1 INST2 COA {year}",
                f"YR1 INST3 COA {year}",
                f"YR1 INST4 COA {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 COA {year}",
                f"YR2 INST2 COA {year}",
                f"YR2 INST3 COA {year}",
                f"YR2 INST4 COA {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 COA {year}",
                f"YR3 INST2 COA {year}",
                f"YR3 INST3 COA {year}",
                f"YR3 INST4 COA {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 113 [C.A.-Eng. Lit.-Pol. Sci.]": {
            "YR1": [
                f"YR1 INST1 COA {year}",
                f"YR1 INST2 COA {year}",
                f"YR1 INST3 COA {year}",
                f"YR1 INST4 COA {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 COA {year}",
                f"YR2 INST2 COA {year}",
                f"YR2 INST3 COA {year}",
                f"YR2 INST4 COA {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 COA {year}",
                f"YR3 INST2 COA {year}",
                f"YR3 INST3 COA {year}",
                f"YR3 INST4 COA {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 116 [Hindi Lit.-History-Pol. Sci.]": {
            "YR1": [
                f"YR1 INST1 GEN {year}",
                f"YR1 INST2 GEN {year}",
                f"YR1 INST3 GEN {year}",
                f"YR1 INST4 GEN {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 GEN {year}",
                f"YR2 INST2 GEN {year}",
                f"YR2 INST3 GEN {year}",
                f"YR2 INST4 GEN {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 GEN {year}",
                f"YR3 INST2 GEN {year}",
                f"YR3 INST3 GEN {year}",
                f"YR3 INST4 GEN {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 117 [History-Func. Hindi-Pol. Sci.]": {
            "YR1": [
                f"YR1 INST1 FEH {year}",
                f"YR1 INST2 FEH {year}",
                f"YR1 INST3 FEH {year}",
                f"YR1 INST4 FEH {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 FEH {year}",
                f"YR2 INST2 FEH {year}",
                f"YR2 INST3 FEH {year}",
                f"YR2 INST4 FEH {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 FEH {year}",
                f"YR3 INST2 FEH {year}",
                f"YR3 INST3 FEH {year}",
                f"YR3 INST4 FEH {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 121 [Func. Eng.-Eco.-Pol. Sci.]": {
            "YR1": [
                f"YR1 INST1 FEH {year}",
                f"YR1 INST2 FEH {year}",
                f"YR1 INST3 FEH {year}",
                f"YR1 INST4 FEH {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 FEH {year}",
                f"YR2 INST2 FEH {year}",
                f"YR2 INST3 FEH {year}",
                f"YR2 INST4 FEH {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 FEH {year}",
                f"YR3 INST2 FEH {year}",
                f"YR3 INST3 FEH {year}",
                f"YR3 INST4 FEH {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 122 [Func. Eng.-History-Pol. Sci.]": {
            "YR1": [
                f"YR1 INST1 FEH {year}",
                f"YR1 INST2 FEH {year}",
                f"YR1 INST3 FEH {year}",
                f"YR1 INST4 FEH {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 FEH {year}",
                f"YR2 INST2 FEH {year}",
                f"YR2 INST3 FEH {year}",
                f"YR2 INST4 FEH {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 FEH {year}",
                f"YR3 INST2 FEH {year}",
                f"YR3 INST3 FEH {year}",
                f"YR3 INST4 FEH {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 123 [Func. Eng.-C.A.-Eco.]": {
            "YR1": [
                f"YR1 INST1 COA {year}",
                f"YR1 INST2 COA {year}",
                f"YR1 INST3 COA {year}",
                f"YR1 INST4 COA {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 COA {year}",
                f"YR2 INST2 COA {year}",
                f"YR2 INST3 COA {year}",
                f"YR2 INST4 COA {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 COA {year}",
                f"YR3 INST2 COA {year}",
                f"YR3 INST3 COA {year}",
                f"YR3 INST4 COA {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 126 [C.A.-Func. Eng.-Pol. Sci.]": {
            "YR1": [
                f"YR1 INST1 FEH {year}",
                f"YR1 INST2 FEH {year}",
                f"YR1 INST3 FEH {year}",
                f"YR1 INST4 FEH {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 FEH {year}",
                f"YR2 INST2 FEH {year}",
                f"YR2 INST3 FEH {year}",
                f"YR2 INST4 FEH {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 FEH {year}",
                f"YR3 INST2 FEH {year}",
                f"YR3 INST3 FEH {year}",
                f"YR3 INST4 FEH {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 128 [C.A.-Func. Hindi-Pol. Sci.]": {
            "YR1": [
                f"YR1 INST1 FEH {year}",
                f"YR1 INST2 FEH {year}",
                f"YR1 INST3 FEH {year}",
                f"YR1 INST4 FEH {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 FEH {year}",
                f"YR2 INST2 FEH {year}",
                f"YR2 INST3 FEH {year}",
                f"YR2 INST4 FEH {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 FEH {year}",
                f"YR3 INST2 FEH {year}",
                f"YR3 INST3 FEH {year}",
                f"YR3 INST4 FEH {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 130 [C.A.-Hindi Lit.-Pol. Sci.]": {
            "YR1": [
                f"YR1 INST1 FEH {year}",
                f"YR1 INST2 FEH {year}",
                f"YR1 INST3 FEH {year}",
                f"YR1 INST4 FEH {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 FEH {year}",
                f"YR2 INST2 FEH {year}",
                f"YR2 INST3 FEH {year}",
                f"YR2 INST4 FEH {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 FEH {year}",
                f"YR3 INST2 FEH {year}",
                f"YR3 INST3 FEH {year}",
                f"YR3 INST4 FEH {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BA 131 [C.A.-Eco.-Pol. Sci.]": {
            "YR1": [
                f"YR1 INST1 COA {year}",
                f"YR1 INST2 COA {year}",
                f"YR1 INST3 COA {year}",
                f"YR1 INST4 COA {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 COA {year}",
                f"YR2 INST2 COA {year}",
                f"YR2 INST3 COA {year}",
                f"YR2 INST4 COA {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 COA {year}",
                f"YR3 INST2 COA {year}",
                f"YR3 INST3 COA {year}",
                f"YR3 INST4 COA {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BSc 203 [Biotechnology-Chemistry-Zoology]": {
            "YR1": [
                f"YR1 INST1 OTH {year}",
                f"YR1 INST2 OTH {year}",
                f"YR1 INST3 OTH {year}",
                f"YR1 INST4 OTH {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 OTH {year}",
                f"YR2 INST2 OTH {year}",
                f"YR2 INST3 OTH {year}",
                f"YR2 INST4 OTH {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 OTH {year}",
                f"YR3 INST2 OTH {year}",
                f"YR3 INST3 OTH {year}",
                f"YR3 INST4 OTH {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BSc 204 [Botany-Chemistry-Ind Microbiology]": {
            "YR1": [
                f"YR1 INST1 OTH {year}",
                f"YR1 INST2 OTH {year}",
                f"YR1 INST3 OTH {year}",
                f"YR1 INST4 OTH {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 OTH {year}",
                f"YR2 INST2 OTH {year}",
                f"YR2 INST3 OTH {year}",
                f"YR2 INST4 OTH {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 OTH {year}",
                f"YR3 INST2 OTH {year}",
                f"YR3 INST3 OTH {year}",
                f"YR3 INST4 OTH {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BSc 205 [Botany-Chemistry-Zoology]": {
            "YR1": [
                f"YR1 INST1 CBZ {year}",
                f"YR1 INST2 CBZ {year}",
                f"YR1 INST3 CBZ {year}",
                f"YR1 INST4 CBZ {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 CBZ {year}",
                f"YR2 INST2 CBZ {year}",
                f"YR2 INST3 CBZ {year}",
                f"YR2 INST4 CBZ {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 CBZ {year}",
                f"YR3 INST2 CBZ {year}",
                f"YR3 INST3 CBZ {year}",
                f"YR3 INST4 CBZ {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BSc 206 [Chemistry-Mathematics-Physics]": {
            "YR1": [
                f"YR1 INST1 PCM {year}",
                f"YR1 INST2 PCM {year}",
                f"YR1 INST3 PCM {year}",
                f"YR1 INST4 PCM {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 PCM {year}",
                f"YR2 INST2 PCM {year}",
                f"YR2 INST3 PCM {year}",
                f"YR2 INST4 PCM {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 PCM {year}",
                f"YR3 INST2 PCM {year}",
                f"YR3 INST3 PCM {year}",
                f"YR3 INST4 PCM {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BSc 207 [Computer Sci-Mathematics-Physics]": {
            "YR1": [
                f"YR1 INST1 OTH {year}",
                f"YR1 INST2 OTH {year}",
                f"YR1 INST3 OTH {year}",
                f"YR1 INST4 OTH {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 OTH {year}",
                f"YR2 INST2 OTH {year}",
                f"YR2 INST3 OTH {year}",
                f"YR2 INST4 OTH {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 OTH {year}",
                f"YR3 INST2 OTH {year}",
                f"YR3 INST3 OTH {year}",
                f"YR3 INST4 OTH {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BSc 209 [Computer App-Mathematics-Physics]": {
            "YR1": [
                f"YR1 INST1 OTH {year}",
                f"YR1 INST2 OTH {year}",
                f"YR1 INST3 OTH {year}",
                f"YR1 INST4 OTH {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 OTH {year}",
                f"YR2 INST2 OTH {year}",
                f"YR2 INST3 OTH {year}",
                f"YR2 INST4 OTH {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 OTH {year}",
                f"YR3 INST2 OTH {year}",
                f"YR3 INST3 OTH {year}",
                f"YR3 INST4 OTH {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "YEARLY BSc 211 [Computer Sc-Economics-Mathematics]": {
            "YR1": [
                f"YR1 INST1 OTH {year}",
                f"YR1 INST2 OTH {year}",
                f"YR1 INST3 OTH {year}",
                f"YR1 INST4 OTH {year}",
                f"YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"YR2 INST1 OTH {year}",
                f"YR2 INST2 OTH {year}",
                f"YR2 INST3 OTH {year}",
                f"YR2 INST4 OTH {year}",
                f"YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"YR3 INST1 OTH {year}",
                f"YR3 INST2 OTH {year}",
                f"YR3 INST3 OTH {year}",
                f"YR3 INST4 OTH {year}",
                f"YR3 EXAM FEE {year+1}",
            ],
        },
        "B.Ed.": {
            "YR1": [
                f"BEd YR1 INST1 {year}",
                f"BEd YR1 INST2 {year}",
                f"BEd YR1 INST3 {year}",
                f"BEd YR1 INST4 {year}",
                f"BEd YR1 EXAM FEE {year+1}",
            ],
            "YR2": [
                f"BEd YR2 INST1 {year}",
                f"BEd YR2 INST2 {year}",
                f"BEd YR2 INST3 {year}",
                f"BEd YR2 INST4 {year}",
                f"BEd YR2 EXAM FEE {year+1}",
            ],
            "YR3": [
                f"BEd YR3 INST1 {year}",
                f"BEd YR3 INST2 {year}",
                f"BEd YR3 INST3 {year}",
                f"BEd YR3 INST4 {year}",
                f"BEd YR3 EXAM FEE {year+1}",
            ],
        },
        # SEMESTER WISE COURSES
        "B.COM": SEM_COMMON_INSTALMENTS,
        "BCA": SEM_COMMON_INSTALMENTS,
        "BBA": SEM_COMMON_INSTALMENTS,
        "BSC (BIOTECHNOLOGY)": SEM_COMMON_INSTALMENTS,
        "BSC (CHEMISTRY)-BIO GROUP": SEM_COMMON_INSTALMENTS,
        "BSC (CHEMISTRY)-MATHS GROUP": SEM_COMMON_INSTALMENTS,
        "BSC (COMPUTER SCIENCE)": SEM_COMMON_INSTALMENTS,
        "BSC (INDUSTRIAL MICROBIOLOGY)": SEM_COMMON_INSTALMENTS,
        "BSC (MATHS)": SEM_COMMON_INSTALMENTS,
        "BSC (PHYSICS)": SEM_COMMON_INSTALMENTS,
        "BSC (ZOOLOGY)": SEM_COMMON_INSTALMENTS,
        "BA (ECONOMICS)": SEM_COMMON_INSTALMENTS,
        "BA (ENGLISH LITERATURE)": SEM_COMMON_INSTALMENTS,
        "BA (HINDI LITERATURE)": SEM_COMMON_INSTALMENTS,
        "BA (HISTORY)": SEM_COMMON_INSTALMENTS,
        "BA (POLITICAL SCIENCE)": SEM_COMMON_INSTALMENTS,
        # PG COURSES
        "MCom 901 [Commerce]": SEM_COMMON_INSTALMENTS,
        "MA 401 [Economics]": SEM_COMMON_INSTALMENTS,
        "MA 402 [English Literature]": SEM_COMMON_INSTALMENTS,
        "MA 403 [Political Sci]": SEM_COMMON_INSTALMENTS,
        "MSc 501 [Physics]": SEM_COMMON_INSTALMENTS,
        "MSc 502 [Microbiology]": SEM_COMMON_INSTALMENTS,
        "MSc 503 [Zoology]": SEM_COMMON_INSTALMENTS,
        "MSc 504 [Chemistry]": SEM_COMMON_INSTALMENTS,
        "MSc 505 [Computer Sci]": SEM_COMMON_INSTALMENTS,
        "MSc 506 [Biotechnology]": SEM_COMMON_INSTALMENTS,
        "MSc 507 [Maths]": SEM_COMMON_INSTALMENTS,
    }

    return INSTALMENTS_PER_COURSE
